### ISSUE TITLE
Put a link the video where you talk about a specific card

### ISSUE THREAD

**Issue by dglaude** [geerlingguy/raspberry-pi-pcie-devices#10]
Just an idea.

**Comment by geerlingguy** [comment]
That's... actually a really good idea. Not sure why I didn't think about that!

**Comment by geerlingguy** [comment]
I'm working on rapidly improving the site over in #41 — moving the rest of this work there.

I am adding links to any videos referencing certain cards on the card details page (when you click through a card's name or thumbnail pic), and eventually I hope to add a little light templating so the video is either embedded or shows a thumbnail from YouTube.
