### ISSUE TITLE
MirkoPC - Tiny CM4 carrier board with full-size M.2 slot

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#101]
Noticed this isn't on the site yet, but looks pretty cool. Very much like the TOFU I just tested, but more targeted towards a desktop use case, and less on the industrial side. It has a 12V input, it also has a built in DAC and RTC battery slot, so it fits the needs of a full-on desktop a little nicer.

![Mirek34416541_2021-Mar-12](https://user-images.githubusercontent.com/481677/111172770-192cd080-8574-11eb-8188-52dbe086960c.jpg)

![Mirek34416541_2021-Mar-12 1](https://user-images.githubusercontent.com/481677/111172781-1b8f2a80-8574-11eb-9faa-5943939e49e6.jpg)

More pics of the first board here: https://twitter.com/Mirek34416541/status/1368839261886283777

**Comment by marzy57** [comment]
Please! swap out the USB 2.0 FOR 3.0

**Comment by TheGuyDanish** [comment]
> Please! swap out the USB 2.0 FOR 3.0

One does not simply add USB 3. Looking at the pictures, it seems he's elected to forego USB 3 to use the PCI-e slot for an NVMe SSD. Adding a PCI-e switch to allow both would take a large amount of space which is already at a premium on the board.

**Comment by geerlingguy** [comment]
Not only that; if you put a PCIe switch in the loop, the beta NVMe boot option doesn't work, too. So you have to sacrifice a bit to get that.

**Comment by punnypenguins** [comment]
Live site page for this board: https://pipci.jeffgeerling.com/boards_cm/mirkopc.html
