### ISSUE TITLE
CM4 Handheld 'Pocket C.H.I.P.'-inspired hardware from Diodes Delight / Adafruit

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#102]
Just found this on Twitter: https://twitter.com/diodesdelight/status/1372209073534418953

![diodesdelight_2021-Mar-17 1](https://user-images.githubusercontent.com/481677/111494433-765b8a00-870c-11eb-8150-1d9baf34c610.jpg)
![diodesdelight_2021-Mar-17](https://user-images.githubusercontent.com/481677/111494446-79567a80-870c-11eb-942c-00c555e1df7b.jpg)

Looks like the design is based around the original idea of the [Pocket C.H.I.P.](https://shop.pocketchip.co/collections/frontpage/products/pocket-c-h-i-p-new) which [ultimately got scuttled](https://shop.pocketchip.co/pages/about).

**Comment by geerlingguy** [comment]
cc @timonsku @adafruit

**Comment by Jonson26** [comment]
Wow, nice! I remember being really sad, when te original C.H.I.P. failed.
