### ISSUE TITLE
Mcuzone CM4_Tiny Dual HDMI Expansion board

### ISSUE THREAD

**Issue by OldDroid** [geerlingguy/raspberry-pi-pcie-devices#105]
Special features:
- USB2.0 Host mode (can be used to program the EMMC directly appearently)
- Camera connector 22 pin
- Dual HDMI
- Gigabit LAN

Found it while browsing on AliExpress today, looks like its new and didn't appear yet on your list!
https://a.aliexpress.com/_vB715r

![-1099917915362315768](https://user-images.githubusercontent.com/2953408/112735650-f58f6000-8f4d-11eb-9efd-f858752e8111.jpg)

**Comment by geerlingguy** [comment]
Thanks! It's hard to track all these new Mcuzone boards :D

**Comment by punnypenguins** [comment]
Live site page for this board: https://pipci.jeffgeerling.com/boards_cm/mcuzone-cm4_tiny.html
