### ISSUE TITLE
ax200 on CM4 not work with NO fastal ERROR.Please help!

### ISSUE THREAD

**Issue by andersling** [geerlingguy/raspberry-pi-pcie-devices#108]
Hi,MR.geerlingguy: I follow you great artical : https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/22 ,try to let ax200 to work on CM4 (OS:ubuntu 20.10,kernel 5.10.25,arm64):
but when it boot up, i try dmesg,it shows:
  
  **ubuntu@ubuntu:~$ dmesg
[  502.110496] Intel(R) Wireless WiFi driver for Linux
[  502.115428] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-cc-a0-59.ucode failed with error -2
[  502.115497] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-cc-a0-58.ucode failed with error -2
[  502.115556] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-cc-a0-57.ucode failed with error -2
[  502.115611] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-cc-a0-56.ucode failed with error -2
[  502.117827] iwlwifi 0000:01:00.0: api flags index 2 larger than supported by driver
[  502.117920] iwlwifi 0000:01:00.0: TLV_FW_FSEQ_VERSION: FSEQ Version: 89.3.35.22
[  502.117948] iwlwifi 0000:01:00.0: Found debug destination: EXTERNAL_DRAM
[  502.117961] iwlwifi 0000:01:00.0: Found debug configuration: 0
[  502.120431] iwlwifi 0000:01:00.0: loaded firmware version 55.d9698065.0 cc-a0-55.ucode op_mode iwlmvm
[  502.182725] iwlwifi 0000:01:00.0: Detected Intel(R) Wi-Fi 6 AX200 160MHz, REV=0x340
[  502.373304] iwlwifi 0000:01:00.0: base HW address: 64:bc:58:04:31:6b
[  502.388423] thermal thermal_zone1: failed to read out thermal zone (-61)**

and no more information of iwlwif that flowing. it's confuzing!~

and when i typed **iw dev** it shows:
   ubuntu@ubuntu:~$ sudo iw dev
phy#4
	Unnamed/non-netdev interface
		wdev 0x400000002
		addr 64:bc:58:04:31:6c
		type P2P-device
		txpower 0.00 dBm
	Interface wlan0
		ifindex 7
		wdev 0x400000001
		addr 64:bc:58:04:31:6b
		ssid JetsonNano
		type managed
		channel 12 (2467 MHz), width: 40 MHz, center1: 2457 MHz
		txpower 22.00 dBm
		multicast TXQ:
			qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcol	tx-bytes	tx-packets
			0	0	0	0	0	0	0	0		0

and the output of lspci is :
ubuntu@ubuntu:~$ sudo lspci -v
00:00.0 PCI bridge: Broadcom Inc. and subsidiaries Device 2711 (rev 20) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0
	Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
	I/O behind bridge: 00000000-00000fff [size=4K]
	Memory behind bridge: c0000000-c00fffff [size=1M]
	Prefetchable memory behind bridge: [disabled]
	Capabilities: [48] Power Management version 3
	Capabilities: [ac] Express Root Port (Slot-), MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [180] Vendor Specific Information: ID=0000 Rev=0 Len=028 <?>
	Capabilities: [240] L1 PM Substates

01:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)
	Subsystem: Intel Corporation Wi-Fi 6 AX200
	Flags: bus master, fast devsel, latency 0, IRQ 50
	Memory at 600000000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: [c8] Power Management version 3
	Capabilities: [d0] MSI: Enable- Count=1/1 Maskable- 64bit+
	Capabilities: [40] Express Endpoint, MSI 00
	Capabilities: [80] MSI-X: Enable+ Count=16 Masked-
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [14c] Latency Tolerance Reporting
	Capabilities: [154] L1 PM Substates
	Kernel driver in use: iwlwifi
	Kernel modules: iwlwifi

any idea? Thanks a lot!

**Comment by geerlingguy** [comment]
Please see https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/22#issuecomment-727087296 — you will need to patch the linux kernel driver and recompile the kernel to get this card to work, and it also needs the iwlwifi firmware appropriate to the card. Please read through that issue for all the details.
