### ISSUE TITLE
KubeSail PiBox - Pi CM4 NAS Box

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#112]
See: https://kubesail.com/blog/pibox-raspberry-pi-powered-nas (and minisite: https://pibox.io)

![blog-pibox-2-mini-render](https://user-images.githubusercontent.com/481677/114437198-d7e80a80-9b8b-11eb-9f53-4362edcab6f3.png)

Still in prototype, but here's the synopsis:

> Today we're announcing the PiBox, a Raspberry Pi powered storage server capable of running tons of great software, like self-hosted alternates to Dropbox and Google Photos. We're happy ship it to you with a vanilla OS, or with Kubernetes and the KubeSail agent pre-installed. KubeSail lets you install new software on your PiBox in a single click, via software templates!

**Comment by geerlingguy** [comment]
cc @PastuDan (and thanks to @rockaut for highlighting this project).

**Comment by PastuDan** [comment]
Thanks @rockaut and @geerlingguy ! We're early in the process of testing some prototype boards, but I'll keep this thread up to date as we make progress!

Right now we've got some boards fully built that prove we're definitely on the right track! We're still having issues with a kernel panic at boot using the JMB582 chip, but the next revision of boards that we're ordering today will use a carrier / daughterboard design that will let us swap out SATA chipsets easily (likely will make a 2-port design around the ASM1061) as well as number of drives.

![F942E08A-434B-42DF-8BF5-F21D9FE17C77](https://user-images.githubusercontent.com/1296162/112647109-c7a30200-8e0d-11eb-82a9-075621c4490d.jpeg)
![44987879-F40C-448E-A955-CDC50E8DDD56](https://user-images.githubusercontent.com/1296162/112647259-ee613880-8e0d-11eb-8134-d77ae26bb32e.jpeg)

**Comment by geerlingguy** [comment]
@PastuDan - Nice; and sorry I haven't gotten around to testing the 2 port chipset—it's literally sitting on top of a small pile of cards I have in the queue after I get through a couple more videos on general CM4 boards that I've been putting off :)

**Comment by geerlingguy** [comment]
@PastuDan - What are the two large connector spaces on the bottom left? (To the left of the HDMI port).

**Comment by PastuDan** [comment]
> @PastuDan - What are the two large connector spaces on the bottom left? (To the left of the HDMI port).

This is an SD slot and Ethernet port, from left to right. The eth port is significantly smaller on the latest revision.

**Comment by PastuDan** [comment]
Latest photos:

![IMG_6703 copy](https://user-images.githubusercontent.com/1296162/124336875-2b4f7080-db5d-11eb-9228-8f8becbb953a.jpg)
![IMG_6706 3 copy](https://user-images.githubusercontent.com/1296162/124336878-2ee2f780-db5d-11eb-893a-e20993c0fc1d.jpg)
![IMG_6710 2 copy](https://user-images.githubusercontent.com/1296162/124336880-2f7b8e00-db5d-11eb-91d5-d906be861cd2.jpg)

**Comment by geerlingguy** [comment]
@PastuDan - Ooh, nice! I like the edge connector for the drives; and I was wondering... that port did look like network, but was way deeper than a typical RJ45 jack, but shallower than SFP+ (and I was thinking it would be odd to stick SFP+ in a consumer NAS!).

**Comment by PastuDan** [comment]
@miztroh pibox.io is the best place for updates. We'll send an update email soon! We've been heads down finalizing prototypes, and we're on track to launch our kickstarter next month

**Comment by miztroh** [comment]
@PastuDan Ok, great.  Thanks for the quick reply.  I'll be on the lookout for the Kickstarter!

**Comment by dragonfly-net** [comment]
Am I correct in understanding that Pibox is dead?

**Comment by SuNNjek** [comment]
@dragonfly-net The website (https://kubesail.com/) says at the bottom that "KubeSail is no longer accepting new users or selling hardware" which is a pretty definitive yes I'd say
