### ISSUE TITLE
Waveshare CM4 IO Base double sided SSD support

### ISSUE THREAD

**Issue by lukechilds** [geerlingguy/raspberry-pi-pcie-devices#126]
Thanks for this absolutely brilliant resource @geerlingguy. Sorry if this is not the appropriate place to post this question. I tried to get in touch with the manufacturer but got no response.

I'm trying to find out if the [Waveshare CM4 IO Base](https://pipci.jeffgeerling.com/boards_cm/waveshare-cm4-io-base.html) supports a double sided SSD like in the image below.

<img width="657" alt="Screenshot 2021-05-01 at 11 36 57" src="https://user-images.githubusercontent.com/2123375/116770956-c77fcd00-aa71-11eb-968b-abcd9108142a.png">

If anyone has any knowledge of this I'd greatly appreciate some information. Thanks!

**Comment by lukechilds** [comment]
My gut tells me the 2230 notch on the board will get in the way:

<img width="994" alt="Screenshot 2021-05-01 at 11 45 58" src="https://user-images.githubusercontent.com/2123375/116771131-36115a80-aa73-11eb-8d9f-f8e6b31a4152.png">

**Comment by geerlingguy** [comment]
I would say likely not—too many things on the board there that would get in the way. A double-sided SSD needs a pretty much flat board underneath.

**Comment by paulwratt** [comment]
an nvme slot extender cable.

or maybe forget the drive, and throw one of these in there instead:
https://www.youtube.com/watch?v=Su3WUNyYklE

(MOTILE 14 NVME M.2 to 16x PCIe adapter)

**Comment by warmwaffles** [comment]
I _just_ ran into this issue today.

**Comment by lukechilds** [comment]
Cheers guys.

>I just ran into this issue today. It does not fit the double sided nvme well. I may try to desolder the shorter screw hole to get it to flush mount.

Thanks for letting us know @warmwaffles. I'll close this issue as it seems like that's a definite no. But if you could update us with how removing the 2230 notch goes I'd really appreciate it!

**Comment by warmwaffles** [comment]
@lukechilds after looking at this a little longer, removing the 2230 notch would gain me a little bit of clearance but there are capacitors and stuff near there that I think will prevent me from having it sit perfectly flush. For now I've just resorted to using kapton tape to hold it down.

**Comment by lukechilds** [comment]
Aww that sucks :/

Thanks for letting me know!

**Comment by warmwaffles** [comment]
@lukechilds or @geerlingguy maybe add a note about double sided nvme use for the waveshare board?

**Comment by geerlingguy** [comment]
@warmwaffles - I don't think it's necessarily important to note—double-sided NVMe are non-standard and (IIRC) out of spec, so there are many devices where they would not physically fit. That's why those SSDs often come with an extra warning (e.g. 'check for fit before purchase!').

**Comment by warmwaffles** [comment]
I definitely did not see that warning / did not pay enough attention to it. 😛

**Comment by piexil** [comment]
Double sided M.2s are in-spec 
https://en.wikipedia.org/wiki/M.2

Under form factors and keyring, S1-S5 for single sided thinkness and D1-D5 for double sided.

**Comment by warmwaffles** [comment]
If the components were not underneath the m.2 slot, it would fit just fine. Although thinking about it now, cooling the memory module against the board may be difficult.

**Comment by geerlingguy** [comment]
@piexil - Ah, well TIL. I will reopen the issue until I or someone else adds a PR to update the docs on that board in particular (maybe with a note like below):

> **Note**: This board's NVMe slot may not work with double-sided M.2 NVMe drives due to clearance issues.

I still think it's risky using double-sided cards unless you have the room for adequate cooling (or blast a fan over that area).

**Comment by dans98** [comment]
An update for everyone.

I purchased the [Waveshare Mini Base Board (B)](https://www.waveshare.com/cm4-io-base-b.htm) and the Sabrent 512gb m.2 from amazon.

The double sided m.2 will not work, as the  2230 screw mount will get in the way. 👎 

Hopefully I can return the drive and find a decent sizes single sided drive.
