### ISSUE TITLE
PCI Passthrough

### ISSUE THREAD

**Issue by ghokun** [geerlingguy/raspberry-pi-pcie-devices#13]
VMWare has released an ARM fling see: https://flings.vmware.com/esxi-arm-edition

I wonder if it is possible to achieve pci passthrough.

Here is an installation video: https://youtu.be/6aLyZisehCU

**Comment by geerlingguy** [comment]
Thanks for the suggestion! I don't have too much interest in trying out ESXi on the Pi, though others who may have more experience/expertise there would be welcome to test things out and see what happens!
