### ISSUE TITLE
Add board TPU cam with CM4

### ISSUE THREAD

**Issue by NitinJSanket** [geerlingguy/raspberry-pi-pcie-devices#142]
Please add the [TPU cam with CM4](https://grabcad.com/library/tpu-cam-with-cm4-1) to the site.

This is an amazing board.

**Comment by geerlingguy** [comment]
Wow, very neat board! Some more background—here are a couple pictures:

![tpu-cam-cm4](https://user-images.githubusercontent.com/481677/119285433-a3925000-bc07-11eb-8d37-a4390e372fb6.png)
![tpu-cam-cm42](https://user-images.githubusercontent.com/481677/119285434-a42ae680-bc07-11eb-8858-dca67ebe5c34.png)

From the description:

> Combination of Coral Edge TPU, Raspberry Pi Compute Module 4 and imx219 camera sensors.

In the [YouTube video about the board](https://www.youtube.com/watch?v=6aQB4FLPs9k), Jakub mentioned Coral was working through a 'PCI Express bus', but I wonder if he's actually got it going through USB 3.0 to PCIe or if he found a way to get it working directly?

See: https://github.com/google-coral/edgetpu/issues/280

**Comment by geerlingguy** [comment]
And here's the project page: https://grabcad.com/library/tpu-cam-with-cm4-1
