### ISSUE TITLE
Benchmark Pi kernel compilation on M1 Mac mini and MacBook Air

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#150]
Just for funsies... I'm trading in my Intel i9 2.4 GHz 2019 16" MacBook Pro for both an M1 Mac mini (with 10Gbps and 16 GB RAM) and an M1 MacBook Air (with 16 GB of RAM) — notably, those two computers cost the same as the amount I can sell the 2019 MBP for _used_!

The 2019 MBP will do about 12.5 minutes cross-compile using the following command on the 5.10.x kernel inside the [Docker-based cross-compile environment](https://github.com/geerlingguy/raspberry-pi-pcie-devices/tree/master/extras/cross-compile):

```
time make -j10 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image modules dtbs
```

I want to see how the Air and mini perform for the same exact command (under qemu) and see what kind of things I can do to optimize build times since the M1 is native ARM/`aarch64`...

**Comment by geerlingguy** [comment]
| Scenario | Time (hh:mm:ss) |
| --- | --- |
| 2019 i9 MacBook Pro - cross-compile | 00:12:30 |
| 2020 M1 MacBook Air - cross-compile | 00:10:23 |
| 2020 M1 Mac mini - cross-compile | TODO |

**Comment by geerlingguy** [comment]
Also wondering if `-j10` might be too much for the optimum mix on the M1 (with it's 4 'performance' + 4 'efficiency' cores).

**Comment by geerlingguy** [comment]
Seems like `-j8` might be optimal on the M1.

**Comment by geerlingguy** [comment]
With `-j8` I'm getting 8:58 on the M1 mini, so yeah, looks like that'll be my new recommendation.

**Comment by geerlingguy** [comment]
<img width="909" alt="m1-vs-i9-linux-kernel-recompile" src="https://user-images.githubusercontent.com/481677/120375925-ec6d9700-c2e0-11eb-911e-ffbad7c4f631.png">

**Comment by geerlingguy** [comment]
Blog post about it: [The Apple M1 compiles Linux 30% faster than my Intel i9](https://www.jeffgeerling.com/blog/2021/apple-m1-compiles-linux-30-faster-my-intel-i9).

**Comment by mwpastore** [comment]
M1 Pro (10-core) 👀 

```
ubuntu@preferable-planthopper:~/linux$ time make -j8 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image modules dtbs
.
.
.
real	6m1.945s
user	41m10.009s
sys	5m36.866s
```

I used [multipass](https://multipass.run/) to create a quick Impish VM with eight cores. It appears to be using the P-cores only. It wouldn't let me create a VM with ten cores.

**Comment by geerlingguy** [comment]
Dang... can you also try with maybe -j10 or -j12 and see if you still get a boost? Usually you can go a little beyond the strict core count, but it depends on the architecture.

Now I want to see how long it takes on some M1 Max Macs (that'll never get old).

**Comment by mwpastore** [comment]
`-j10`:

```
real	5m15.496s
user	36m10.306s
sys	4m47.460s
```

`-j12`:

```
real	5m27.698s
user	37m44.642s
sys	4m53.749s
```

So yeah, 5-ish minutes. Nice.

> Now I want to see how long it takes on some M1 Max Macs (that'll never get old).

It might be a bit faster due to the increased memory bandwidth (and capacity) but probably not that much faster.

**Comment by geerlingguy** [comment]
True, CPU cores are the same.

**Comment by ericcurtin** [comment]
I always go with -j number of cores even on x86. Even if it's faster with more parallelism it's nice to spare a few CPU cycles for other stuff

**Comment by ericcurtin** [comment]
Would someone mind running a quick test for me building with multipass vs docker vs podman on the M1? I might be buying a Mac mini in the next few days for work. I want to see what the performance is like between these tools. The slowness of my raspberry pi is becoming a bottleneck for me?

**Comment by mwpastore** [comment]
> multipass vs docker vs podman on the M1

Docker on macOS runs in a VM, so don't expect too much performance difference between these options.

**Comment by paulwratt** [comment]
> The slowness of my raspberry pi is becoming a bottleneck for me

get more Raspberry Pi's
