### ISSUE TITLE
Lite Berry

### ISSUE THREAD

**Issue by TroopaShells** [geerlingguy/raspberry-pi-pcie-devices#152]
Lite berry is a cm4 board to turn a 3rd party  Lite housing  into a retro handheld. Currently just a kickstarter.  I have been working on this for some time recently got a 3rd party to design and test pcb. 

https://github.com/TroopaShells/Lite-Berry/

https://www.kickstarter.com/projects/troopashells/lite-berry/posts.

**Comment by TroopaShells** [comment]
![20210612_150602](https://user-images.githubusercontent.com/65099090/121825204-0747f000-cc7f-11eb-8c96-ebe72fdd7291.jpg)

**Comment by geerlingguy** [comment]
@TroopaShells - I would be happy to put up something on the site once there's more content including a PCB design rendering or full prototype—right now there's not enough to go on to give people the information they'd need to learn from the build or much assurance the full product will exist once the Kickstarter is funded.

Please feel free to reopen or open a new issue once you have more information or renders to add.

**Comment by TroopaShells** [comment]
Alright . I understand completely.
