### ISSUE TITLE
uCM4 (Minimal CM4 carrier board)

### ISSUE THREAD

**Issue by just-grizzle** [geerlingguy/raspberry-pi-pcie-devices#163]
I stumbled upon the uCM4 carrier board on [Hackaday](https://hackaday.io/project/179793-ucm4)  recently. It is intended as the "smallest possible headless server with help of Compute Module 4 unit."

![8051941621864919907](https://cdn.hackaday.io/images/8051941621864919907.jpg)

Features:
- exactly same size as CM4
- support for both Lite and eMMC variants of CM4
- Gigabit Ethernet
- microSD slot (optional)
- Micro USB for power and USB 2.0 data transfer
- USB-OTG support

See it in action [here](https://www.youtube.com/watch?v=mftScuGE_xw) .

**Comment by geerlingguy** [comment]
Very neat! I also liked your little micro USB connector flip about 20 seconds in on the video. Should definitely get this added to the site. Do you have any open source design files for this, or is it planned to be sold anywhere or offered as a kit?

**Comment by just-grizzle** [comment]
Hey Jeff, I'm not the inventor of this board. Just came across it and thought it could be nice on your list.

But I found his [repo on Github](https://github.com/v3l0c1r4pt0r/ucm4). Can't watch the ZIP on mobile, but the name indicates there are pcb files inside.
