### ISSUE TITLE
Uptime Labs' upberry - Tiny CM4 carrier

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#170]
The [Upberry](https://www.instagram.com/p/CQga-_YL5OL/) is a tiny CM4 carrier with only HDMI, USB-C for power and OTG support, and status and activity LEDs:

![208375692_850963938843862_5413032309171463334_n](https://user-images.githubusercontent.com/481677/124492873-a2ae1b80-dd7a-11eb-95a6-3ae8b9d35595.jpg)

![207220113_321863769433288_1063555643278285564_n](https://user-images.githubusercontent.com/481677/124492892-a5107580-dd7a-11eb-8e17-6b2e03ac606b.jpg)

There will be a machined aluminum case that keeps with the trim aesthetic, and it should be able to fit in as a tiny display computer, or something like a Chromecast, if you have a WiFi version on the CM4.

**Comment by geerlingguy** [comment]
It's on the site now!

**Comment by mazyargholami** [comment]
Where can I found this product or kicad file?
