### ISSUE TITLE
Add EDATEC CM4 Industrial Computer

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#172]
The [EDATEC CM4 Industrial Computer](http://www.edatec.cn/en/Product/Camera_Modules/2019/0826/76.html) is a CM4 carrier and metal enclosure that provides a number of helpful interfaces for the Pi CM4, like separate 10/100 and 1 Gbps Ethernet ports, access to all GPIO and I/O connections from the CM4 SoC, a built-in relay, 2x DI, 2x RS485, RS232, 3x ADC, RTC and Fan controllers, a SIM card slot and PCIe slot for modules like 4G LTE modems, and more.

![1-210615164344300](https://user-images.githubusercontent.com/481677/124947451-74784800-dfd5-11eb-85a6-e0b6b77f1e62.png)

![1-210615164421112](https://user-images.githubusercontent.com/481677/124947472-78a46580-dfd5-11eb-9821-c5198c52b942.png)

![1-2106151A012410](https://user-images.githubusercontent.com/481677/124947523-835efa80-dfd5-11eb-95eb-fa2421d07647.jpg)

**Comment by punnypenguins** [comment]
Live site page for this board: https://pipci.jeffgeerling.com/boards_cm/edatec-cm4-industrial-computer.html
