### ISSUE TITLE
Add ATX Watchdog for Compute Module 4

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#174]
The [ATX Watchdog for CM4](https://www.tindie.com/products/tomtibbetts/atx-watchdog-for-compute-module-4/) is an ATX power supply that stacks on the IO Board's HAT connection and provides 12V/3A power to the CM4 via the 4-pin berg/floppy power connector, plus 12/5VDC (3A... at what voltage?) screw terminals to power other project circuits in addition to the Pi.

![2021-05-24T23-43-32 115Z-20210213_150806_cropped_1](https://user-images.githubusercontent.com/481677/125488973-2790cf3d-7948-4497-b82d-707681d86892.jpg)

![2021-05-24T23-51-17 206Z-20210213_143649_cropped](https://user-images.githubusercontent.com/481677/125489008-70a39b93-c830-489d-850d-6c465b5df0d8.jpg)

It also includes a watchdog timer, safe shutdown capability, and a lighted power button.

**Comment by punnypenguins** [comment]
Live site page for this board: https://pipci.jeffgeerling.com/boards_cm/atx-watchdog-cm4.html
