### ISSUE TITLE
Add BitScope systems to watch list

### ISSUE THREAD

**Issue by IshtarIS** [geerlingguy/raspberry-pi-pcie-devices#180]
I have purchased a Bitscope Micro Cluster (www.bitscope.com) with 4 x Pi 4 8G's and have been working through your Ansible for DevOps using the cluster (with two extra Pi Zero's and a Pi 3B+).   They also do some much much larger clusters.  
![DSC_5527](https://user-images.githubusercontent.com/86140961/126869016-1622c3f3-fee0-421f-a81d-b03b79cf285a.JPG)

**Comment by geerlingguy** [comment]
While they do have some pretty cool systems, these are running on commodity CM4s and aren't related to PCI Express bus integration, or CM4 boards, so I won't be adding it to the site.
