### ISSUE TITLE
Add Raspberry Pi CM4 TV Stick

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#181]
The [Raspberry Pi CM4 TV Stick](https://hackaday.io/project/180969-raspberry-pi-cm4-tv-stick) is a carrier that plugs directly to HDMI port. Perfect for Kodi, RetroPie, or just using a Pi attached directly to a monitor or TV for any use case. Power is through USB-C, though.

![6804181627425557784](https://user-images.githubusercontent.com/481677/127421415-70821799-4073-4043-afd2-f72e2c2e1324.jpeg)

Hat tip to [Matthew Turland](https://twitter.com/elazar/status/1420511405460148232) for the link.

**Comment by magic-blue-smoke** [comment]
GitHub home for this project: https://github.com/magic-blue-smoke/Raspberry-Pi-CM4-TV-Stick
Twitter: https://twitter.com/magic__smoke (double underscore)
Boards are in production now and expected to be available for purchase late September.
Production boards will be 2mm longer to fit ambilight connector. Status LEDs moved from the edge under CM4 to the edge around USB-C connector. Third USB port available as solder pads "just in case"

**Comment by geerlingguy** [comment]
@magic-blue-smoke - Excellent, thanks for posting the updated info! And for making this board, it looks great!

**Comment by geerlingguy** [comment]
Page: https://pipci.jeffgeerling.com/boards_cm/raspberry-pi-cm4-tv-stick.html
