### ISSUE TITLE
Add Uptime Lab's MinCab minimal CM4 carrier board

### ISSUE THREAD

**Issue by just-grizzle** [geerlingguy/raspberry-pi-pcie-devices#193]
Hey,

just read about the MinCab CM4 board over at [CNXSoft](https://www.cnx-software.com/2021/08/10/mincab-smallest-raspberry-pi-cm4-carrier-board/) .

![MinCab-Rapsberry-Pi-CM4](https://user-images.githubusercontent.com/66440907/128848157-8ef771ed-e1b9-46af-8d95-551000788fdb.jpg)

It would nicely fit on your list of CM4 boards.
Even though the articles links towards the UpLab website, I could not find any information there. But as you have good connections, you'll surely find out more. 

Regards and until next time!

**Comment by geerlingguy** [comment]
Yes, I noticed Ivan posted about it on Twitter too: https://twitter.com/Merocle/status/1424701350567350276

> Regards and until next time!

Heh.

I think the MinCab takes the crown of the smallest possible CM4 carrier board now!

**Comment by just-grizzle** [comment]
That's for sure. But I don't get the use case yet. Like it though.

**Comment by geerlingguy** [comment]
Added!
