### ISSUE TITLE
Add Intel I210 NIC - supports hardware PTP timestamping

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#204]
In tandem with my work on the Time Card (see #199), I noticed @lasselj had tested the [Intel I210](https://amzn.to/3jscEb4) on a Raspberry Pi and it seems to be working:

![131358775-701269cc-3f0f-4aca-a6ed-e1583b7a1b08](https://user-images.githubusercontent.com/481677/131525388-cedb78bf-6a69-43ad-b737-2f77b05e3baf.jpeg)

@lasselj - I was wondering, did you have to do anything special to get Intel's driver to work on Pi OS in your testing?

**Comment by lasselj** [comment]
@geerlingguy It's [this](https://thepihut.com/products/metal-enclosure-for-raspberry-pi-compute-module-4-io-board-with-cooling-fan) case. Kudos to whomever decided to make this slice in the case to make a standard PCIe card fit:
<img width="150" alt="kudos" src="https://user-images.githubusercontent.com/12864656/131991683-b10c9b0a-c658-4e0e-b5f4-eb4d8966206b.png">

**Comment by geerlingguy** [comment]
Added to the site!

**Comment by antevens** [comment]
For future reference I think it's probably worth noting that the I210 (and from what I can tell any device using the Intel igb driver) can't send ONESTEP PTP packets, it can only do two step.

**Comment by coconutneu** [comment]
> For future reference I think it's probably worth noting that the I210 (and from what I can tell any device using the Intel igb driver) can't send ONESTEP PTP packets, it can only do two step.

Can you provide more details on this? This is the description from the datasheet of i210
7.8.2.2.4 1-step Time Synchronization Phase Procedure
Packet processing in the master and the Slave for 1-step procedure is almost identical to the 2-step procedure as follow:
• The master software sends the SYNC packet while indicating it to the hardware by the 1STEP_1588 flag. Doing so, the hardware inserts the transmission time in the SYNC packet.
• The slave samples the reception time of the SYNC and extract its transmission time at the master.
• From this point the flow is identical to the 2-step procedure.
So from this, it seems that the I210 should be capable of sending 1-step SYNC packets via hardware. Or maybe I'm wrong?

**Comment by antevens** [comment]
It's been a while since I looked at this, I remember trying to get onestep to work and recompiling but the hardware simply never sent it.

In the end I gave up on using an RPi and had to revert back to a hardware GM source for our gNodeBs.

**Comment by lasselj** [comment]
Hi. So I don't remember the exact details for the i210 (odds are the same), but for the i225/i226, the issue is that whereas the hardware can update the sync timestamp, it cannot recalculate the UDP header checksum. I once submitted kernel patches to enable then layer 2 PTP one-step, but Richard Cochran turned them down on netdev for what I at the time considered no compelling reason. As my life is definitely too short to quarrel with him, I never revisited. Use 2-step. It works just as well in 99.5% of cases.

**Comment by coconutneu** [comment]
Hi, thanks a lot for sharing these insights! I’ve made some driver modifications myself, but unfortunately the one-step functionality still doesn’t seem to be working correctly. If you happen to have any guidance or tips on that, I’d be truly grateful.

**Comment by lasselj** [comment]
@coconutneu It should be in the netdev mailing list archive, but I’m happy to have a look and forward patches. Please bear with me 🙂
