### ISSUE TITLE
Add Mini SS Main Board for CM4 Lite

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#206]
I just learned about the [Mini SS Main Board](https://retrogamerestore.com/store/minisscm4/) from Retro Game Restore in [this video from ETA Prime](https://www.youtube.com/watch?v=mVlgFyst3OA).

![6BA41C5A-7BD1-4B89-A5E2-88324E840C6E](https://user-images.githubusercontent.com/481677/131714211-00358c8f-20f0-45a0-9d31-a5ce7d7dc3e6.jpeg)

![9F367603-7BA3-42C6-8DC7-D710010A6EC3](https://user-images.githubusercontent.com/481677/131714239-5f3abd38-3435-4052-85db-aebf3d5e7a8a.jpeg)

The Mini SS supports mini HDMI and CRT (Composite and RGBS) output. There's a planned extension board that would also give 1 Gbps network and a connector for the original Sega Saturn A/V cable.

It's made to fit inside the [Best HIT Chonicle 2/5 SEGASATURN](https://amzn.to/38ve8uP) case, which is available for $33 on Amazon.

**Comment by punnypenguins** [comment]
Live site page for this board: https://pipci.jeffgeerling.com/boards_cm/mini-ss-main-board-cm4-lite.html
