### ISSUE TITLE
Add Chipsee AIO-CM4-156

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#213]
I just noticed the [Chipsee AIO-CM4-156](https://chipsee.com/product/aio-cm4-156/) in a recent ETA Prime video, [A New All In One Raspberry Pi CM4 Desktop PC!](https://www.youtube.com/watch?v=bSvZ-cUcbCY):

![aio-156-side-2](https://user-images.githubusercontent.com/481677/132037742-426c5982-116c-463f-9225-3b57249f213e.jpg)

<img width="1820" alt="Screen Shot 2021-09-03 at 11 22 11 AM" src="https://user-images.githubusercontent.com/481677/132037758-6d268ede-e07f-4b2d-b92c-93c58a3fcdc9.png">

The AIO-CM4-156 is an all-in-one desktop computer based on Raspberry Pi CM4. It includes two USB 3.0 ports, a full-size HDMI port (so you can have a 2nd external display), 1 Gbps Ethernet, a microSD card slot, 3.5mm audio output, and a full 40 pin GPIO port. Internally, there's also an NVMe SSD M.2 slot (SSD optional). The screen can be made to be a touchscreen, optionally, and the enclosure includes built-in speakers.

**Comment by punnypenguins** [comment]
Live site page for this board: https://pipci.jeffgeerling.com/boards_cm/chipsee-aio-cm4-156.html
