### ISSUE TITLE
Add BladeBerry CM4 blade server board

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#220]
This is in the prototype stage, but has a lot of similarities (though is a bit simpler than) the Uptime.Lab CM4 Blade server. It's the 'BladeBerry':

![BladeBerryv1 0](https://user-images.githubusercontent.com/481677/132244401-80866250-d1d8-419c-b315-03035e1b0c8b.jpg)

It has PoE+, M.2 NVMe SSD, microSD slot for Lite modules, <5W power consumption. Find out more on Robert Gálik's twitter: https://twitter.com/RobertGalik2008/status/1427645511679492116

**Comment by geerlingguy** [comment]
Added to the site!

**Comment by MrDJinDK** [comment]
Looks like this board will be up for sale here soon: https://beby.cloud/en/
