### ISSUE TITLE
Add Storinator Jr (which uses the LSI 9405W-16i and an IO Board)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#252]
The Storinator Jr. includes _16_ 2.5" SATA drives, a CM4 on the official IO Board, and an [LSI 9405W-16i HBA](https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/196). It is limited to around 400 MiB/sec storage throughput, but since it only has 1 Gbps Ethernet, that's not going to be a bottleneck if you just use it for network storage.

![45Drives_2021-Sep-12](https://user-images.githubusercontent.com/481677/133488053-0e315152-0c34-4694-b257-87cf65851a73.jpg)

Related YouTube video: https://www.youtube.com/watch?v=A6X9ci8KvgE

45Drives even compiled in ZFS and did some benchmarking—it wasn't amazingly performant, but it did work :)

To get to production, they would need to do some extra performance validation, change the SSD mounting orientation, and possibly switch to a DC power input jack.

**Comment by Therealjosephchrzempiec** [comment]
I really wish they would make this. I know people say it started out as a joke. But still I think ththing be a great server box. Yes it might not be all that fast and truth be told neither is some of Synology and qnap servers are that fast as well.
