### ISSUE TITLE
Wrong header for the "Renesas uPD720201 USB 3.0 controller".

### ISSUE THREAD

**Issue by TMillesich** [geerlingguy/raspberry-pi-pcie-devices#257]
The Renesas has the header "MZHOU USB 3.0 adapter with M.2 SATA SSD slot" listed, but the Renesas has no M.2 SATA functionality.

Compare the header
https://pipci.jeffgeerling.com/cards_usb/mzhou-usb3-sata-iii.html
with
https://pipci.jeffgeerling.com/cards_usb/renesas-UPD720201-usb3-6amlifestyle.html

**Comment by punnypenguins** [comment]
@TMillesich Thanks so much for catching this! I'm sending in a pull request to change it ASAP.

**Comment by rtreffer-sc** [comment]
Oh, I only had a USB only device

**Comment by geerlingguy** [comment]
Fixed!
