### ISSUE TITLE
Adding Renesas Electronics mPCIe D720202 USB 3.0 host controller

### ISSUE THREAD

**Issue by almeyras** [geerlingguy/raspberry-pi-pcie-devices#264]
Hello and sorry if this is not the right place. I am quite new to Github.

![XT-XINTE-MINI-PCI-E-a-USB3-0-tarjeta-elevadora-PCI-Express-de-2-puertos-a jpg_Q90](https://user-images.githubusercontent.com/481677/135493862-bb4c059c-e016-489e-b609-85e722d6b279.jpg)

I tested a mPCIe card with the Renesas Electronics D720202 USB 3.0 host controller ([manufacturer page](https://www.renesas.com/us/en/products/interface-connectivity/usb-switches-hubs/upd720202-usb-30-host-controller) | [Aliexpress link](https://es.aliexpress.com/item/32847876690.html?spm=a2g0s.9042311.0.0.b2c063c0LQqdvF)). It worked flawlessly (no drivers or kernel recompiling involved in Raspberry OS 10 Buster, `arm_64bit=1`). Both 3.0 and 2.0 devices tested. This is interesting since if you use this kind of card along with mPCIe switch (RB14eU in my case), you can plug more mPCIe devices without sacrificing the ability to connect USB 3.0 peripherals.

The only inconvenience I run into was having to provide 5V voltage. mPCIe slots only have 3.3 volt inputs, so this card bundles a [berg plug](https://en.wikipedia.org/wiki/Berg_connector) _("floppy connector")_ for powering the USB devices (the D720202 appears in `lsusb` and `lspci`, put no USB device will work unless you power the berg plug). Since the CM4 I/O Board bundles another berg plug, you just have to connect them together.

Some insights about powering the CM4 I/O Board:
- If you use the barrel jack to power the CM4 with a 12 V supply, the berg I/O board connector will provide the expected voltages: 5 V, gnd, gnd, 12 V.
- If you use a Pi PoE Hat (tested 2018 PoE version, not newer PoE+), the berg I/O board connector will provide: 5 V, gnd, gnd, 5 V **(no 12 V!)**. But the USB card and your USB devices will work anyway.

Just connect both berg plugs in the same order and everything will be fine (it doesn't matter whether you use PoE or barrel jack). Bear in mind that if you use a standard ATX PSU, you will have to plug it to the barrel jack using some adapter intead of the onboard berg. 

Trying to power the USB 3.0 card with the I/O board 5V USB 2.0 header didn't work (maybe I made some mistake). I can post some pictures of working setups if you want.

**Comment by geerlingguy** [comment]
Card is up on the site. Thanks!
