### ISSUE TITLE
Add MikroTik RB14eU (PCIe 2.0 switch PEX8606)

### ISSUE THREAD

**Issue by almeyras** [geerlingguy/raspberry-pi-pcie-devices#267]
![](https://i.mt.lv/cdn/rb_images/670_l.jpg)

[Official product page](https://mikrotik.com/product/RB14eU#fndtn-downloads).

This card converts one full size PCIe 1x to four mPCIe slots. It uses the PCIe switch [Broadcom PEX 8606](https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/pex8606), with a capacity for up to six PCI Express Gen 2 (5.0 GT/s) lanes. Broadcom suggests two hardware configurations: 1 lane for host + 5 for cards OR 2 lanes for the host + 3 for cards. Since the RB14eU is PCIe **1x** 2.0, there is no point in using two lanes for the host. The configuration chosen for MikroTik is 1 lane for host + 4 for cards, leaving one lane unpopulated. 

This card does not require any driver or kernel recompiling. This is the `lspci` output of a CM4 with this card (all 6 lanes appear):

```
00:00.0 PCI bridge: Broadcom Limited Device 2711 (rev 20)
01:00.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:01.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:04.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:05.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:07.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:09.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
```

The card also bundles a miniSIM card slot and USB 2.0 auxiliary connection for each of the four mPCIe slots. USB is provided by your carrier board by any of this possibilities:

- Four USB pin headers for all four mPCIe sockets.
- Two microUSB type B for two mPCIe sockets and two USB type A (male) for the other two sockets.
- Combinations of the previous options.

It includes USB internal cables that you can use with the CM4 I/O board USB pin headers. Keep in mind that the I/O board has pins everywhere while there should be a "no pin" in one corner. You will have to identify it (It's the closest to the microUSB connector) and cut the pin or drill a hole in the connector. Red shirt Jeff will guide you here.

![](https://i.stack.imgur.com/qPoTU.jpg)

There is a trimmed down version of this card without miniSIM or USB called [RB14e](https://mikrotik.com/product/RB14e). You should avoid it if you intend to use mPCIe peripherals that are actually USB like LTE modems or LoRaWAN concentrator cards.

The card comes with two back plates: one for low profile (with 6 antenna plug holes) and a normal one (with 9 holes). 

This card has been my favourite since I bought my CM4. It works like a charm. No issue with PoE hat powering (I did not try PoE+). You can attach extra adapters for M.2 NGFF peripherals. I tried  key A, E, and M.

Official MSRP is 59$ or 49$ without USB. This card has been officially discontinued but you can still find it online in many places at a very low price. I got mine in [Landashop for 20€+VAT+shipping](https://www.landashop.com/en/mikrotik-routerboard-14eu.html).

**Comment by geerlingguy** [comment]
Thanks for all the details. Definitely a nice alternative to an elaborate board like the [Alftel 12x card](https://pipci.jeffgeerling.com/cards_m2/alftel-12x-pcie-m2-carrier-board.html) if you just need a few slots!

**Comment by geerlingguy** [comment]
Card has been added!

**Comment by nipegun** [comment]
> ![](https://camo.githubusercontent.com/79bee24ef42460bc12c9a09c510b5a00a149d7868eee7934a3f0ce90baf18e1f/68747470733a2f2f692e6d742e6c762f63646e2f72625f696d616765732f3637305f6c2e6a7067)
> 
> [Official product page](https://mikrotik.com/product/RB14eU#fndtn-downloads).
> 
> This card converts one full size PCIe 1x to four mPCIe slots. It uses the PCIe switch [Broadcom PEX 8606](https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/pex8606), with a capacity for up to six PCI Express Gen 2 (5.0 GT/s) lanes. Broadcom suggests two hardware configurations: 1 lane for host + 5 for cards OR 2 lanes for the host + 3 for cards. Since the RB14eU is PCIe **1x** 2.0, there is no point in using two lanes for the host. The configuration chosen for MikroTik is 1 lane for host + 4 for cards, leaving one lane unpopulated.
> 
> This card does not require any driver or kernel recompiling. This is the `lspci` output of a CM4 with this card (all 6 lanes appear):
> 
> ```
> 00:00.0 PCI bridge: Broadcom Limited Device 2711 (rev 20)
> 01:00.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
> 02:01.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
> 02:04.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
> 02:05.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
> 02:07.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
> 02:09.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
> ```
> 
> The card also bundles a miniSIM card slot and USB 2.0 auxiliary connection for each of the four mPCIe slots. USB is provided by your carrier board by any of this possibilities:
> 
>     * Four USB pin headers for all four mPCIe sockets.
> 
>     * Two microUSB type B for two mPCIe sockets and two USB type A (male) for the other two sockets.
> 
>     * Combinations of the previous options.
> 
> 
> It includes USB internal cables that you can use with the CM4 I/O board USB pin headers. Keep in mind that the I/O board has pins everywhere while there should be a "no pin" in one corner. You will have to identify it (It's the closest to the microUSB connector) and cut the pin or drill a hole in the connector. Red shirt Jeff will guide you here.
> 
> ![](https://camo.githubusercontent.com/2815e4a8cf1087f0ca706ef247a755f320dd9a6ddd5676b88608b52d624e4104/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f71506f54552e6a7067)
> 
> There is a trimmed down version of this card without miniSIM or USB called [RB14e](https://mikrotik.com/product/RB14e). You should avoid it if you intend to use mPCIe peripherals that are actually USB like LTE modems or LoRaWAN concentrator cards.
> 
> The card comes with two back plates: one for low profile (with 6 antenna plug holes) and a normal one (with 9 holes).
> 
> This card has been my favourite since I bought my CM4. It works like a charm. No issue with PoE hat powering (I did not try PoE+). You can attach extra adapters for M.2 NGFF peripherals. I tried key A, E, and M.
> 
> Official MSRP is 5or49 without USB. This card has been officially discontinued but you can still find it online in many places at a very low price. I got mine in [Landashop for 20€+VAT+shipping](https://www.landashop.com/en/mikrotik-routerboard-14eu.html).

There is a chinese alternative for this card. I`ll post the name if I remember where to find it.

**Comment by ohault** [comment]
Anyone has already tried to configure this card to use the [Broadcom PEX 8606](https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/pex8606) on-chip Non-Transparent port for dual-host ?

Goal : to provide a support of [Linux PCIe Non-Transparent Bridge (NTB) ](https://github.com/jonmason/ntb)for small labs

**Comment by Hipska** [comment]
This card is discontinued. Shop also doesn't work anymore.
