### ISSUE TITLE
Add Utility Control Unit

### ISSUE THREAD

**Issue by H3ndrik-Jan** [geerlingguy/raspberry-pi-pcie-devices#281]
### Utility Control Unit
The utility control unit is a DIN-rail mountable 3D-printer/smart home server, developed by @bauke2012 and @H3ndrik-Jan. The system consists of two PCB's stacked on top of each other, fitted into a small (6 DIN-modules wide) enclosure. The unit has a beefy power supply (12V input), USB 3.0 host controller, outputs for controlling relays, RS485 connection, can read out a current transformer, control LED-strips including WS2812B's, inputs for buttons, and has all fast IO of the CM4 (like gigabit ethernet, HDMI) accessible on the front.
More information on the project can be found here: https://hackaday.io/project/181244-utility-control-unit
![photo_2021-08-17_20-02-26](https://user-images.githubusercontent.com/46112431/137384989-b3bce0ac-07f6-4e89-a5dc-012724823643.jpg)
![IMG_0106](https://user-images.githubusercontent.com/46112431/137384904-d80bf4a5-043a-4aaf-aa42-8545492eb5dd.JPG)
![IMG_0102](https://user-images.githubusercontent.com/46112431/137384825-14b50650-6ed2-4fc9-b4f1-f87c54bc6214.JPG)
)
![IMG_0103](https://user-images.githubusercontent.com/46112431/137384852-b42196d0-eeb3-4289-8352-3beab161f058.JPG)

**Comment by geerlingguy** [comment]
On the site: https://pipci.jeffgeerling.com/boards_cm/utility-control-unit.html
