### ISSUE TITLE
Add CM4 to Pi 4B Adapter board from AliExpress

### ISSUE THREAD

**Issue by jamesy0ung** [geerlingguy/raspberry-pi-pcie-devices#285]
I was browsing AliExpress and saw this Raspberry Pi CM4 to PI4B Adapter board. From what I see, it mimics the layout of the Raspberry Pi 4B except it has 4 USB 3.0 ports instead of 2.

![Raspberry-Pi-CM4-to-PI4B-Adapter-eMMC-Boot-4-x-USB-3-0-TF-Slot-Gigabit jpg_Q90 jpg_ webp](https://user-images.githubusercontent.com/481677/138107581-a246babe-88ea-4f73-bb2f-adb0b82b5346.png)

https://www.aliexpress.com/item/1005003389500589.html?spm=a2g0o.productlist.0.0.5a0b661aWNGaU6&algo_pvid=ea1afd6c-74d9-4115-8274-1b2592668a86&algo_exp_id=ea1afd6c-74d9-4115-8274-1b2592668a86-4&pdp_ext_f=%7B%22sku_id%22%3A%2212000025554881568%22%7D

**Comment by punnypenguins** [comment]
Live site page for this board: https://pipci.jeffgeerling.com/boards_cm/mii-store-cm4-adapter-board.html

**Comment by jamesy0ung** [comment]
whoops, forgot to close issue long ago.
Closed.
