### ISSUE TITLE
Add 52Pi CM4 Router Board

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#293]
S2Pi's [CM4 Router Board](https://www.seeedstudio.com/CM4-Router-Board-p-5211.html) is an expansion board based on the Raspberry Pi Compute Module 4. It has two full-speed gigabit network ports and offers better performance, lower CPU usage, and higher stability for a long time work compared with a USB network card. Designed especially for OpenWRT.

![103110042_preview-07](https://user-images.githubusercontent.com/481677/140854717-41318003-9ceb-4da3-a8a8-589dc9df40a4.jpg)

**Comment by paulwratt** [comment]
S2Pi's what? ;)

**Comment by geerlingguy** [comment]
@paulwratt - Oopsie! Got it fixed.

Honestly until this year I always thought it was S2 Pi, because of the stylized logo.
