### ISSUE TITLE
Add CurryPi CM4 Cluster Board

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#296]
The CurryPi CM4 Cluster board was hinted at in @aep's [Twitter post](https://twitter.com/arvidep/status/1445363759313297412):

![FA72rZcXoAIB8qQ](https://user-images.githubusercontent.com/481677/141157495-c13d1840-f166-48fb-bdb1-98ebbfe0eaa7.jpeg)

It's a 4-node CM4 cluster board. It looks like each Pi gets an M.2 NVMe slot, and each node gets its own network jack on the rear. [Looking at the project's GitHub repository](https://github.com/devguardio/currypi), it seems like there is some active development and improvements to the board's power management are underway.

**Comment by hipboi** [comment]
Yeah, Curry Pi is also applying the Radxa CM3 for the project. The additional SATA will be the benefit. Let's see how it goes.
