### ISSUE TITLE
Add gpio.base Raspi CM4

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#299]
From taskit, the [gpio.base Raspi CM4](https://www.taskit.de/en/products/raspberry-pi/pi4pro/327/gpio.base-raspi-cm4) allows a huge array of modular industrial IO in a compact form factor, and there is also a [starterkit](https://www.taskit.de/en/products/raspberry-pi/pi4pro/328/gpio.base-raspi-cm4-starterkit) variety which includes three of the most common IO boards:

![starterkit-gpio-portux-cm4_mit_cm4_modul_swtch_4260578797030_600x600@2x](https://user-images.githubusercontent.com/481677/141350861-5af9837c-464c-4975-b4dd-697c25e4719b.png)

![gpio-portux-cm4_mit_cm4_modul_top_4260578795203](https://user-images.githubusercontent.com/481677/141350924-26c495aa-679e-4e27-9e52-6679b20da07c.png)

**Comment by punnypenguins** [comment]
Live site page for this board: https://pipci.jeffgeerling.com/boards_cm/gpio-base-raspi-cm4.html
