### ISSUE TITLE
Add will whang's CM4 Pi 4 Cluster HAT

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#303]
@will127534 is back with a [CM4 Pi 4 Cluster HAT](https://twitter.com/will_whang/status/1459080800314425345) which is by far the most compact and powerful Pi cluster on the planet, packing four Compute Module 4s onto a HAT the size of a Pi 4 model B, and it even throws in a Raspberry Pi Pico for management tasks!

![will_whang_2021-Nov-12](https://user-images.githubusercontent.com/481677/141593644-cdae03c7-acd2-49c6-a9ad-44e0483d2fd8.jpg)

It uses a built-in Gigabit network switch to provide networking to all the CM4s, and you can find more details in [@will_whang's introductory Twitter thread](https://twitter.com/will_whang/status/1459080800314425345).

**Comment by will127534** [comment]
Here is the [Github repo](https://github.com/will127534/Miniature-CM4-Cluster/) and  [Github Page](https://will127534.github.io/Miniature-CM4-Cluster/)!

Thanks @geerlingguy for adding this to the list!

**Comment by geerlingguy** [comment]
@punnypenguins - Could you update the PR with those links? Thanks!

**Comment by punnypenguins** [comment]
@geerlingguy Done!
