### ISSUE TITLE
Add RPi4-RTC-PoE DIN rail mini server

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#309]
The [RPi4-RTC-PoE](https://www.tindie.com/products/megad-2561/rpi4-rtc-poe/) DIN rail mini server offers PoE power, Gigabit Ethernet, USB 2.0, USB-over-Ethernet, an M.2 2230 slot for NVMe SSDs, a power button, status LEDs, an RTC, hardware watchdog, RS485, and ZigBee, and is a very compact little DIN server.

![2021-11-12T00-57-08 317Z-RPi4-RTC-PoE](https://user-images.githubusercontent.com/481677/142014247-59cd7cfe-6d0c-4e70-a898-9e1da84928e3.jpg)

**Comment by ervotech** [comment]
Hi, 
Are there any further developments?

**Comment by Ermakov** [comment]
Hi! I'm one of RPi40RTC-PoE's developers. Yes, we still producing this device in some volumes and selling in Russia and other closest countries. But deliver to western countries is so promlematic for now.

**Comment by geerlingguy** [comment]
@Ermakov - Thank you for the update! And I hope that someday this will change, I love the engineering on your device!
