### ISSUE TITLE
Ensure all board listings have the correct front matter 

### ISSUE THREAD

**Issue by punnypenguins** [geerlingguy/raspberry-pi-pcie-devices#311]
Will add a checklist of which ones need fixing as I go through and check all the board entries.

**Comment by punnypenguins** [comment]
`_boards_cm` entries that need their front matter edited: 

- [ ] 45drives-storinator-jr.md 
- [ ] radxa-taco.md (only needs period added on short description)
- [ ] sega-game-gear-drop-in-retropie-kit.md (missing short description)

**Comment by geerlingguy** [comment]
Fixed!
