### ISSUE TITLE
Add Miniture CM4 Cluster board

### ISSUE THREAD

**Issue by ProKn1fe** [geerlingguy/raspberry-pi-pcie-devices#340]
* https://will127534.github.io/Miniature-CM4-Cluster
* https://github.com/will127534/Miniature-CM4-Cluster

<img src="https://i.imgur.com/k63rKBx.jpg" />
<img src="https://i.imgur.com/DtqzbrF.jpg" />
<img src="https://i.imgur.com/t5aGn2S.jpg" />

**Comment by geerlingguy** [comment]
This is already noted in #303 and will be added via https://github.com/geerlingguy/raspberry-pi-pcie-devices/pull/305 — sorry, just haven't had time to commit that yet, but will soon!
