### ISSUE TITLE
Test Home Assistant Yellow (formerly 'Amber')

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#343]
I added the Amber in https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/253, but the name has been changed to 'Home Assistant Yellow' (see: https://www.home-assistant.io/blog/2021/09/13/home-assistant-yellow/).

![DSC05031](https://user-images.githubusercontent.com/481677/145639567-388c8120-af9e-43c7-b222-13ba69cb0e78.jpeg)

I just got the one pictured above in the mail and would like to test it, especially with my existing Hue bulbs, my AirGradient DIY air quality sensors (maybe using ESPHome?), etc.

**Comment by geerlingguy** [comment]
Technically it's on the site... I just need to update the listing to read 'Yellow' instead of 'Amber'.

**Comment by punnypenguins** [comment]
You want to close this now since you added the file updates for it in Issue #253 the other day?

**Comment by geerlingguy** [comment]
@punnypenguins - No, still need to test it :)

**Comment by punnypenguins** [comment]
Live site page for this board: https://pipci.jeffgeerling.com/boards_cm/home-assistant-yellow.html
