### ISSUE TITLE
Add blicube's bliKVM CM4 IO Board for Pi-KVM

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#345]
blicube is making a [bliKVM CM4 IO Board for Pi-KVM](https://www.aliexpress.com/item/1005003262886521.html?spm=a2g0o.store_pc_allProduct.8148356.5.39cd62bejpZaWF).

![blikvm8](https://user-images.githubusercontent.com/481677/146126095-52a75ce5-6a2e-48a5-8598-cc33090c6ecb.jpg)

![1-1](https://user-images.githubusercontent.com/481677/146126123-1116fcc5-0134-441c-99e5-4a381a4f8eab.png)

![1-2](https://user-images.githubusercontent.com/481677/146126141-484e6035-a6c0-47ec-abb8-2ec507687bd8.png)

The bliKVM integrates seemingly everything from the PiKVM v3 HAT into one compact package that fits in an even smaller space, and doesn't require as complicated an assembly process. Currently the board is priced at $80, the case at $25, or a combo pack with case, fan, OLED display, and board at $100. Pretty good deal!

**Comment by geerlingguy** [comment]
It's on the site!

**Comment by bryanvaz** [comment]
@geerlingguy any plans on testing this?

I'm eyeing this very much. Apparently the next version will have POE. I also left them a suggestion to make it rack-friendly (1U and all ports on one side).

Also are you aware of any other PiKVM boards supporting the CM4? I couldn't find any with a web search, but maybe another developer dropped you a note?

Cheers,
Bryan

**Comment by geerlingguy** [comment]
So far nothing else for Pi-KVM itself, but I do have a couple units of BliKVM and will be testing them soon—I even give the thing a shout out at the end of the video I'll be posting tomorrow morning at 9 on my YouTube channel ;)

**Comment by geerlingguy** [comment]
FYI here's a link to a github repo for the board: https://github.com/ThomasVon2021/pikvm-CM4-Board

**Comment by PhilipTS** [comment]
> So far nothing else for Pi-KVM itself, but I do have a couple units of BliKVM and will be testing them soon—I even give the thing a shout out at the end of the video I'll be posting tomorrow morning at 9 on my YouTube channel ;)

@geerlingguy waiting patiently for your video (or should I say impatiently)

**Comment by geerlingguy** [comment]
Heh... I have it all put together and was going to record something today but the snowstorm through the midwest may delay that :(

**Comment by PhilipTS** [comment]
@geerlingguy well I am a very impatient guy so I pressed the BUY button. So now I can patiently wait for you video :)

**Comment by acarbonaro** [comment]
Can you use a pair of these devices to control each other?  I could see this being useful for folks who run redundant Pi-Hole and/or PiVPN installs.  It would be nice to be able to recover (or at least diagnose) an instance from the other.

**Comment by paulwratt** [comment]
> @geerlingguy well I am a very impatient guy so I pressed the BUY button. So now I can patiently wait for you video :)

Can't remember if I heard the _bliKVM_ mentioned in the video, but I decided "5 left" was enough of an incentive (ooh my 1st CM4)

**Comment by geerlingguy** [comment]
Forgot to mention, the video is up on the Geerling Engineering channel: https://www.youtube.com/watch?v=3OPd7svT3bE

**Comment by punnypenguins** [comment]
Live site page for this board: https://pipci.jeffgeerling.com/boards_cm/blikube-blikvm-cm4-io-board.html
