### ISSUE TITLE
Add Retroflag GPi CASE 2 for CM4

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#350]
Retroflag is out with their new [Retroflag GPi CASE 2](https://amzn.to/3GYUSF8), which packs a CM4 into a Gameboy-style enclosure with USB-C charging, HDMI output, a 3.0" LCD, headphone out, and 2 USB 2 ports.

![71j9gppzlKL _AC_SL1500_](https://user-images.githubusercontent.com/481677/146699677-bfa49a3c-5fa1-4a14-9d6f-fa71db1cfea0.jpg)

It's for sale on Amazon at $79.99.

**Comment by geerlingguy** [comment]
ETA PRIME video: https://youtu.be/zKjYSbHKjhQ

**Comment by micklen** [comment]
Can you run the GPi 2 with a radax or Pine equivalente CM?
