### ISSUE TITLE
Add Mirko's BitPiRat Computer (Gen 2)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#363]
Mirko's [BitPiRat Computer (Gen 2)](https://hackaday.io/project/183430-bitpirat-computer-gen20) is the smallest CM4 carrier board that crams a full-size M.2 NVMe slot on the underside, as well as a bevy of IO on the topside.

![DSC06239](https://user-images.githubusercontent.com/481677/149984791-882ab87c-b085-465c-a7ca-d7fe406cf15b.jpeg)

![DSC06240](https://user-images.githubusercontent.com/481677/149984806-5bb39891-7971-4b71-997b-83e44640098b.jpeg)

![DSC06233](https://user-images.githubusercontent.com/481677/149984815-7b9981f2-5c47-4e48-a5ad-e7910be5b922.jpeg)

It comes with a DSI display connector, mini HDMI, two fan connectors (one with PWM control), Gigabit Ethernet, USB 2.0 OTG (for power and flashing eMMC modules), a boot mode selector, a 16-pin GPIO header, a QWIIC connector, two user-programmable LEDs, a microSD card slot for Lite modules, and a full-size 2280 M.2 M-key NVMe slot.

**Comment by geerlingguy** [comment]
It's on the site! Will also make an appearance in tomorrow's video.

**Comment by olvier** [comment]
Please add status [DEPRECATED], there is no way to "order" it, because project died. UNFORTUNATELY.
Was my favorite board, because size, network and nvme. But was to late for order one.

R.I.P.       -.-

**Comment by msgilligan** [comment]
They can be ordered here: https://dtvelectronics.com/store/

**Comment by prepsin** [comment]
Full project info is now on github here:

https://github.com/DTVElectronics/cmrat
