### ISSUE TITLE
Add Piunora to production boards

### ISSUE THREAD

**Issue by timonsku** [geerlingguy/raspberry-pi-pcie-devices#383]
Hey! You already have Piunora in the prototype list but it is by now shipping and can be ordered :)
Right now only CrowdSupply but Seeedstudio, Adafruit and Pimoroni will follow soon.

Website: https://www.diodes-delight.com/products/piunora/
Docs: https://www.diodes-delight.com/docs/piunora/
I'm updating the suppliers there as they get stock.

**Comment by geerlingguy** [comment]
Good idea, I haven't done a full tracking of all the things in prototype that finally made it to production! We'll get it updated (or you can submit a PR if you feel inclined ;)

**Comment by timonsku** [comment]
Ah missed that this was actually the repo do that in. Added a PR with updated photo and all :)

**Comment by geerlingguy** [comment]
Fixed via #385
