### ISSUE TITLE
Add Sharp / NEC MPi4 NEC MediaPlayer Kit

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#386]
Sharp / NEC displays has a [MPi4 NEC MediaPlayer Kit](https://www.sharpnecdisplays.eu/p/uk/en/products/accessories/details/t/options/computing/rp/raspberrypi-compute-module4.xhtml) available that connects a Raspberry Pi directly into one of their display solutions using their modular display system:

![Sharp-NEC-Display-Solutions_NEC_RPi4_web](https://user-images.githubusercontent.com/481677/153672174-68386c65-d0e5-4902-85cc-5b71209b53a7.jpg)

Meant for digital signage applications, the board comes preinstalled with NEC MediaPlayer, and there's a version with WiFi and an external antenna connector for wireless use.

**Comment by geerlingguy** [comment]
Here's a video on the display's full feature set (mentions the Pi integration at 2:23): https://www.youtube.com/watch?v=zr4WQ8dhhG8

**Comment by bam80** [comment]
I couldn't find info about the NEC MediaPlayer, is it open-source?
