### ISSUE TITLE
Add Delock Module MiniPCIe SM750 VGA/DVI/HDMI Graphics Card

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#398]
Similar to the ASRock Rack M2_VGA, this Mini PCIe board uses the SM750 to power multi-display graphics with a fairly limited GPU. But support for the chip is built into the kernel, via an experimental driver.

![58dbaea7ecb1c0 62030214](https://user-images.githubusercontent.com/481677/155368764-a624abf3-2f93-44c6-9859-bda1bd51e2a6.jpg)

Over in [this issue](https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/62#issuecomment-1046319009), @TobleMiner got the card to at least work with a framebuffer console on the CM4.

**Comment by paulwratt** [comment]
cool, more potential graphics cards, and 2 outputs no less (makes 4 with 2x HDMI, and 5 if there is a 40 pin GPIO header on the carrier board). I wonder how well these types of Graphics cards work in a PCIe slot extender?
