### ISSUE TITLE
Add Waveshare CM4 Nano Base Board (CM4-Nano-B)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#435]
Waveshare recently introduced the [CM4 Nano Base Board (B)](https://www.waveshare.com/CM4-NANO-B.htm), which sits within the CM4 footprint and offers full GPIO, Ethernet, USB 2.0 Type A, mini HDMI, CSI/DSI, 3.5mm Audio Output, and USB-C input for power:

![CM4-NANO-B-details-1](https://user-images.githubusercontent.com/481677/165172022-f35bc5a0-2c1c-4b55-9eaf-6dfd28ef5e1b.jpg)

**Comment by geerlingguy** [comment]
h/t to https://twitter.com/peter_mount/status/1518684491400847361

**Comment by geerlingguy** [comment]
On the site: https://pipci.jeffgeerling.com/boards_cm/waveshare-cm4-nano.html

**Comment by marcusstenbeck** [comment]
Any plans on testing this board? Ports and form factor is perfect for me but I'm seeing varying reviews on Amazon.

**Comment by clomads** [comment]
I tried two variants of OpenWRT (Rooter Goldenorb & SmoothWAN) and both of them stalled right after ethernet check. I'm using a lite/no-wifi. Official 64-bit release from Rpi works just fine. Only had it for a day so more testing to do.
