### ISSUE TITLE
Add to CM4 board list: RAKwireless WisGate Connect

### ISSUE THREAD

**Issue by xoseperez** [geerlingguy/raspberry-pi-pcie-devices#490]
[RAKwireless](https://www.rakwireless.com/en-us) is known for our LoRaWAN Gateways (and Helium hotspots). Now we have just released our first CM4-based gateway, the RAK7391 WisGate Connect. It has been designed to be a flexible edge gateway platform and support multiple wireless & wired connectivity options. I has been tested using LoRaWAN, 4G, Zigbee, WiFi HaLow, WiFi6, Modbus, Canbus,... and more in the future.

Some features:

- Accepts the complete range of CM4 modules
- 2x WisBlock IO connectors (https://store.rakwireless.com/pages/wisblock)
- 3x MiniPCIe slots (SPI, USB, I2C and PCIe interfaces)
- 1x M.2 B-Key interface (USB and PCIe interfaces)
- Flexible power supply modes such as DC terminal, Phoenix terminal and PoE (optional)
- Full size HDMI 2.0 connector
- 1 Gb Ethernet with PoE support (using an optional PoE module)
- 2.5 Gb Ethernet
- 1x USB2.0 port
- 2x USB3.0 ports
- MIPI DSI display FPC connector (22 pin 0.5 mm pitch cable)
- 2x MIPI CSI-2 camera FPC connectors (22 pin 0.5 mm pitch cable)
- Raspberry Pi HAT connector
- Onboard RTC, ADC, temperature sensor, fan driver and extra IO via two GPIO expanders.
- I2C connector for the OLED screen available in indoor enclosures

![IMG_20220902_101516cs](https://user-images.githubusercontent.com/706487/198521277-79171cad-9557-4ab9-839d-76eab9c3968f.jpg)

There are multiple modules and accessories compatible with the WisGate Connect. We have also 3 different enclosures: an aluminum desktop enclosure, a sheet metal one in 1U size to rack, and an outdoors enclosure.

![WisGateConnectAluminum](https://user-images.githubusercontent.com/706487/198525306-02c1b5fa-3945-4fdb-9388-5445147a4b2c.png)

![WisGateConnectOutdoors](https://user-images.githubusercontent.com/706487/198525315-9a60a699-9d85-490e-8da1-0fd5cc526f81.png)

![WisGateConnectSheetmetal](https://user-images.githubusercontent.com/706487/198527049-ffe62dec-2271-4bc7-a429-8213d97abcd5.png)

Resources:

- Info about the product: https://docs.rakwireless.com/Product-Categories/WisGate/RAK7391/Overview/
- Store: https://store.rakwireless.com/products/wisgate-connect-base-kit-rak7391

**Comment by geerlingguy** [comment]
![DSC09731](https://user-images.githubusercontent.com/481677/199791420-ab9eb36b-cd95-4848-bc45-71d303b452b5.jpeg)

I just received a WisGate Connect with an outdoor enclosure, and will begin testing it soon! It seems like a very well-built unit, and the WisBlock expansion capability makes it pretty plug-and-play for IoT endpoints. I'll probably include this in my next CM4 video.

**Comment by geerlingguy** [comment]
Wow, been a while... but I'm finally going to release a video with this in it! Hopefully in a day or two.

**Comment by geerlingguy** [comment]
This is now on the site: https://pipci.jeffgeerling.com/boards_cm/wisgate-connect.html
