### ISSUE TITLE
Add EDATEC CM4 Sensing Computer

### ISSUE THREAD

**Issue by JohnZong66** [geerlingguy/raspberry-pi-pcie-devices#500]
The [EDATEC CM4 Sensing Computer](https://www.edatec.cn/en/Product/Embedded_Computers/2021/0930/132.html) is an industrial computer designed for IoT & Data Acquisition  applications based on Raspberry Pi Compute Module 4.
It provides 4G/LTE module, 4 channels RS485,1 channel RS232, 1 channel CAN, 1 channel Gigabit Ethernet port, alarm buzzer ,battery-powered real-time clock, 2 channels USB2.0 and 1 channel Micro USB2.0 interface.  

![ed-cm4sen-interface-diagram-top](https://user-images.githubusercontent.com/108601084/211245661-cddb0a04-68b0-4a4d-9c86-b2b540746768.png)  

![ed-cm4sen-interface-diagram-bottom](https://user-images.githubusercontent.com/108601084/211245684-f13f03a7-da23-4de0-84ac-ed5521f4985f.png)  

![cm4sen-pcba-001](https://user-images.githubusercontent.com/108601084/211245694-d4788530-6c56-4e8f-8636-60ebadfedb9c.jpg)

**Comment by JohnZong66** [comment]
Good day. I am John from EDATEC. Below is the link to my submit pull request. Could you help check it? Thank.
[Add EDATEC CM4 Sensing Computer](https://github.com/geerlingguy/raspberry-pi-pcie-devices/pull/501)

**Comment by geerlingguy** [comment]
@JohnZong66 - Thanks! This is now on the site: https://pipci.jeffgeerling.com/boards_cm/edatec-cm4-sensing-computer.html
