### ISSUE TITLE
Nebra CM4 Flashstick

### ISSUE THREAD

**Issue by shawaj** [geerlingguy/raspberry-pi-pcie-devices#520]
Thought this might be of interest. You can buy it, but it is also OSHW :-)

![Nebra-Compute-Module-4-1_2000x2000](https://user-images.githubusercontent.com/481677/231327672-adffea9f-180a-4dd1-a7e6-09b21fe912af.jpg)

https://github.com/NebraLtd/FlashStick
https://www.nebra.com/products/nebra-raspberry-pi-cm4-flash-stick
https://github.com/NebraLtd/FlashStick/tree/main/Raspberry_Pi_Compute_Module_4

**Comment by shawaj** [comment]
@geerlingguy so it has two modes - usb boot or emmc boot (i.e. you can use it as a compute stick as well as a flasher).

But yes you still need to use the usbboot stuff. Just that Etcher and EtcherPro have that built in and automatically recognise the compute module

**Comment by geerlingguy** [comment]
> Etcher and EtcherPro have that built in and automatically recognise the compute module

I didn't realize that! https://blog.balena.io/etcher-now-with-multi-write-and-compute-module-support/

I would love to have one of these on hand—would make it even easier than the PiTray mini that I currently use, as I could just slap this into the USB 3 port I have hanging off my Mac, when I need to mess with an eMMC CM4.

**Comment by shawaj** [comment]
Sure thing @geerlingguy we have plenty of them in the warehouse, and CM3 ones too :-)

Can you ping an email with your address to support@nebra.com and a link to this github issue and then let me know the ticket number. Then I'll handle the rest.

Also let us know if there's any other products you might be interested in playing around with on nebra.com or pi-supply.com :-)

**Comment by shawaj** [comment]
And re EtcherPro - yeah it's super handy. We use them in manufacturing for our Helium Miners to program thousands of SD cards and CM3+ ... Very handy!

**Comment by geerlingguy** [comment]
@shawaj - Nice! I emailed that support address but haven't gotten a response.

**Comment by shawaj** [comment]
No worries, I've found the ticket #417021 :-)

I sent a reply a bit earlier

**Comment by shawaj** [comment]
Just checking you received the package ok @geerlingguy ?

**Comment by geerlingguy** [comment]
@shawaj - I did! I have stashed it into a small box with a couple other CM4-based products I'm hoping to get to after I can get my new office buildout underway... right now too many things cluttering up my shelves to get to a compendium video!

**Comment by geerlingguy** [comment]
Page: https://pipci.jeffgeerling.com/boards_cm/nebra-cm4-flashstick.html
