### ISSUE TITLE
Add Pi4GPU ('PiG') PCIe Raspberry Pi CM4 board

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#525]
I just announced the prototype [Pi4GPU](https://github.com/geerlingguy/pi4gpu) in a [YouTube video](https://www.youtube.com/watch?v=l9dItRUjQ0k):

![pi4gpu](https://user-images.githubusercontent.com/481677/231889884-407f870d-cd5b-495a-86b5-0f9ff69d1c26.jpeg)

![pi4gpu-edge](https://user-images.githubusercontent.com/481677/231889886-122ecb19-215e-46ed-a0fe-4d0a705f1bff.jpeg)

This board is a collaboration between [Mirek of Mirkotronics](https://twitter.com/Mirko_DIY) and [Jeff Geerling](https://www.jeffgeerling.com).

The PCIe x4 (physical - only x1 connected signals) card is meant to slot into a special adapter board that allows plugging up to a x16 PCI Express card (mainly intended for graphics cards) directly into this card for testing purposes.

The card exposes 1 Gbps Ethernet, full-size HDMI, two USB 2.0 ports, and a 12v barrel plug on the back. It has a USB-C port for programming on the inside edge, as well as a 6-pin PCIe pinout power input so it can be powered internally or from the same power supply used to power the card under test.

**Comment by geerlingguy** [comment]
It's on the site now! https://pipci.jeffgeerling.com/boards_cm/pi4gpu.html

**Comment by micklen** [comment]
Where can I get PIG card?
