### ISSUE TITLE
IEEE 1284 parallel port no go

### ISSUE THREAD

**Issue by garlick** [geerlingguy/raspberry-pi-pcie-devices#54]
We tested a couple of IEEE 1284 parallel port PCIe cards and failed.  Details at worlickwerx/pi-parport#50.

It seems that this type of card only offers an IO mapped PCIe BAR and the Broadcom PCI bridge doesn't support those.
(Perhaps in retrospect that's a big DUH! but thought  it might be worth documenting somewhere for others)

**Comment by geerlingguy** [comment]
@garlick - Thanks for posting! Yeah, the IO BAR does not work at all on the Pi, so any card/drivers that depend on that working will not work on the Pi :(

I will try to get this added to the site soon!
