### ISSUE TITLE
Add Johann's Carrier Board

### ISSUE THREAD

**Issue by jonnyh64** [geerlingguy/raspberry-pi-pcie-devices#540]
![johanns-carrier-board](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/60403537/201299a7-4d70-4b7f-806b-7d4ee93751a1)

**Comment by jonnyh64** [comment]
See https://github.com/geerlingguy/raspberry-pi-pcie-devices/pull/541

**Comment by geerlingguy** [comment]
Added via the submitted PR. Thank you!

**Comment by geerlingguy** [comment]
https://pipci.jeffgeerling.com/boards_cm/johanns_carrier_board.html

**Comment by geerlingguy** [comment]
@jonnyh64 - Just wondering - do you plan on selling the board, or releasing any more details / schematics for it on GitHub or elsewhere? I can't find any more details besides what's on this repo/site.

**Comment by jonnyh64** [comment]
Perfect, thanks :-)
