### ISSUE TITLE
CM4Ext Nano versions

### ISSUE THREAD

**Issue by gabyavra** [geerlingguy/raspberry-pi-pcie-devices#55]
Hello,

Will be multiple versions available?
For instance I'm looking for something minimalistic, with only two usb C (on only data, on for data+power), the user switch, micro sd.

**Comment by geerlingguy** [comment]
@gabyavra - Please leave questions / comments over on the CM4Ext Nano page here: https://github.com/harlab/CM4Ext_Nano/issues/1
