### ISSUE TITLE
Add Pi 5 HAT: 52Pi PCIe x1 Slot HAT

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#566]
According to [this tweet](https://twitter.com/tltangliang/status/1732244831160942708), 52Pi has built a PCIe x1 open-ended slot HAT for Pi 5, which allows switching between internal power (leeched off the GPIO pins it seems), or external power (using a 4-pin molex floppy power connector like on the CM4 IO Board).

![GAoqiN7a0AAzJii](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/481677/f5af6d05-9220-47af-a18c-3a9ebbdaeffb)

No details on release or pricing just yet.

**Comment by tltangliang** [comment]
![fb6aea88923f0880ddab59c4c85b5a0](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/3a870166-5488-45cd-b72e-8d9ff5723e6e)

![0eeb0e118c7e3227e4a932522044788](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/2e37b02b-b703-4530-8bb3-1f7757f6430d)

<img width="748" alt="7126aaf3c66f96b5fd0666868f12211" src="https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/c290b1b6-f5d7-4667-9cb9-5f4984d853a2">

**Comment by tltangliang** [comment]
![7484665b13aa1df94f08e0c1ab041f1](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/928edcf2-1edb-4cea-a876-3353640d9f18)

**Comment by tltangliang** [comment]
I used it to test a standard PCIe 2.5G network card, the chip is RTL8125bg.
![ae2cd28c89ab81b99790c6cd2f8bd64](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/9a94e0dd-40f0-4b44-a558-bafe089f2516)

The network card was recognized correctly, the IP was obtained successfully。
<img width="876" alt="69711516bd5c8c64c8f0a3bbd155932" src="https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/9c0a235c-1929-4614-b137-e31deee5741b">



The speed handshake was normal when checked with ethtool, and the network speed was normal when tested with iperf3.
<img width="876" alt="d2a088a210e11c7daaf516080d70e69" src="https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/d974a5e4-c1f6-4ce5-b4d8-eee77279b2ba">
<img width="876" alt="e6e74c7ab67fc6bec6fb3b7a8f49100" src="https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/dedcaa7d-1591-4da5-b0b3-e32d6065c78b">

**Comment by leobsky** [comment]
I'm looking forward to get one, please let us know when is ready for sale.

**Comment by tltangliang** [comment]
> I'm looking forward to get one, please let us know when is ready for sale.

@leobsky 52pi says it'll ship around the beginning of February.

**Comment by geerlingguy** [comment]
The board has been added to the site here: https://pipci.jeffgeerling.com/hats/52pi-pcie-x1-slot-hat.html

**Comment by geerlingguy** [comment]
Closing, but will add any more information to this issue as I see fit!
