### ISSUE TITLE
Add Pi 5 HAT: Pineberry Pi Hat AI!

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#567]
Pineberry Pi announced a new [Hat AI!](https://pineberrypi.com/products/hat-ai-for-raspberry-pi-5) this week, which allows for any M.2 E-key variant to be used with Pi 5 (e.g. Coral TPU, most WiFi devices, some 5G / LTE devices).

![TOP1](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/481677/83d7048a-5c6f-4045-a840-a1f3e6dc343d)

**Comment by geerlingguy** [comment]
The board has been added to the site: https://pipci.jeffgeerling.com/hats/pineberry-pi-hat-ai.html

I also have one on hand, and will hopefully get a chance to test it soon!

**Comment by geerlingguy** [comment]
Closing, but will add any more information to this issue as I see fit!

**Comment by anghelcatalingeorge** [comment]
Did you had a chance to test it with the dual TPU from Coral ?

**Comment by anghelcatalingeorge** [comment]
I am waiting for my Hat AI to arrive. But for sure one device is working, the A+E Key with single TPU ( ref: https://youtu.be/so8_h0EKPWU?si=MDB6uR5KzGZZgxDB)

**Comment by frederik** [comment]
> I tried, but no coral card is recognized despite that HatAI card power led is lit. Contacted hatAI support couple of weeks ago but still no response

Not sure, we have/had the same issue, but mine did magically appear after I upgraded Pi OS to the latest packages.

In case this helps anyone (I am on a Pi 5 with the Pineberry PI hat with the A+E Key with the single TPU):

* make sure the cables are in the right orientation (contacts must face the Pi, arrow must line up)
* enable PCIe (I enabled Gen3 as well) https://www.raspberrypi.com/documentation/computers/raspberry-pi-5.html#enabling-pcie
* update PI OS to the latest version (this fixed it for me) (apt-get update and then upgrade)

lspci:
```
[..]
0000:01:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
[..]
```

**Comment by crowd-ctrl** [comment]
Thx @frederik! I had the same issue and could solve it by updating to the newest Pi OS...

**Comment by Reddimus** [comment]
Hey, ya'll I appreciated this post. However, I recently created a [Raspberry Pi 5 - Google Coral Edge M.2 TPU installation guide](https://gist.github.com/Reddimus/c6948d08a4f4b54ee9d075270bd79c3b) that does not require docker, can run natively, has a newer Python version (3.9.16), and has the PyCoral library.
