### ISSUE TITLE
52Pi NVDAC - 2230/2242 NVMe and PCM5122 DAC HAT for RPi5

### ISSUE THREAD

**Issue by tltangliang** [geerlingguy/raspberry-pi-pcie-devices#582]
the combination of NVMe and HiFi. One HAT solves the storage and playback of hifi music

![52pi-nvdac-hat-a01](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/b83c2d03-e9cf-4902-9a89-4b23e5aac7e4)

**Comment by geerlingguy** [comment]
Added! https://pipci.jeffgeerling.com/hats/52pi-nvdac-hat-a01.html
