### ISSUE TITLE
52Pi NVDigi - 2230/2242 NVMe and WM8804 Digi HAT for RPi5

### ISSUE THREAD

**Issue by tltangliang** [geerlingguy/raspberry-pi-pcie-devices#583]
the combination of NVMe and HiFi. One HAT solves the storage and playback of hifi music
![52pi-nvdigi-hat-a02](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/16f2f480-a3f3-4ec5-99bd-2061c92232e9)

**Comment by geerlingguy** [comment]
Added! https://pipci.jeffgeerling.com/hats/52pi-nvdigi-hat-a02.html

Thanks :)
