### ISSUE TITLE
Add 52Pi PD Power  HAT

### ISSUE THREAD

**Issue by tltangliang** [geerlingguy/raspberry-pi-pcie-devices#587]
The Raspberry Pi 5 power requirements are 5V 5A PDO, which common PD power sources cannot satisfy. This PD HAT from 52pi has a built-in DC-DC converter, supporting a wide voltage input of 9-24V or a PD power input of 9-20V. It outputs a maximum power of 5V 8A and supports the 5V 5A PDO of the Raspberry Pi 5. It seems that there's no need to purchase a dedicated power adapter for the Pi 5 separately.

![hat-52pi-pd-power-hat](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/20035159/97c53a15-a9ca-405e-a166-dba176c55e7e)

**Comment by geerlingguy** [comment]
Thanks! I have the board listed on the site now: https://pipci.jeffgeerling.com/hats/52pi-pd-power-hat.html

And with that extra circuitry, it's kinda no wonder Pi didn't want to try to build in full PD support for 9v/12v/etc on the board!

**Comment by YunXi1027** [comment]
Where can I buy it ?

**Comment by tltangliang** [comment]
52pi hasn't hit the shelves yet, guess it's soon, should be in the next couple weeks

**Comment by YunXi1027** [comment]
Ok, thank you for your reply

**Comment by marekcygan** [comment]
Is it possible to buy?

**Comment by dhlavaty** [comment]
Photos here and at https://pipci.jeffgeerling.com/hats/52pi-pd-power-hat.html are different. Seems like different HATs to me.
