### ISSUE TITLE
Add Pineberry Pi HatNET! 2.5G

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#617]
The [Pineberry Pi HatNET! 2.5G](https://pineberrypi.com/products/hatnet-2-5g-2-5-gigabit-ethernet-for-raspberry-pi-5) is a 2.5 Gigabit NIC for the Raspberry Pi 5.

![radxa-penta-sata-hat-3](https://github.com/geerlingguy/raspberry-pi-pcie-devices/assets/481677/fc1f7e19-2e64-4dec-ae8f-677467d93342)

It uses the Realtek RTL8125BG NIC, and the same Ethernet jack that's on the Pi 5 itself. It works out of the box, no driver installation is necessary on Raspberry Pi OS, though you may need to enable the PCI external port by adding `dtparam=pciex1` to the end of the `/boot/firmware/config.txt` file and rebooting.

**Comment by NotizMe** [comment]
It's actually here on the site: https://pipci.jeffgeerling.com/hats/pineboards-hatnet-2.5g.html

**Comment by geerlingguy** [comment]
Thanks!
