### ISSUE TITLE
Test Windows on ARM with PCI-e devices

### ISSUE THREAD

**Issue by Shanduur** [geerlingguy/raspberry-pi-pcie-devices#7]
This might by little bit harder to accomplish, as (as far as I am aware) no one booted Windows 10 on Pi CM4 yet.

**Comment by deltabeard** [comment]
I've found a guide at https://www.windowslatest.com/2020/02/09/heres-how-windows-10-runs-on-raspberry-pi-4-and-3/

**Comment by willfaust** [comment]
They may not be possible because I doubt Nvidia and AMD have released windows arm drivers...

**Comment by Marcinoo97** [comment]
currently uefi has no support for pci-e devices so Windows 10 on CM4 is not worth testing untill its added.

**Comment by geerlingguy** [comment]
Yeah I initially looked at [WoR](https://www.worproject.ml) a bit a few days ago, but it seemed like it would not overcome some of the X86-based PCI limitations that the SoC is going to present. I'm not sure if I want to go down that rabbit hole, especially since compared to Linux, my familiarity with the actual guts of Windows I'd have to dig around in is about 1%.

**Comment by PixlRainbow** [comment]
> They may not be possible because I doubt Nvidia and AMD have released windows arm drivers...

They might not have released them to the public, but they might be in Microsoft's device driver database, which will allow automatic installation through Windows Update. Even if they aren't, Windows still has built-in "standard VGA" drivers to handle video output on generic cards without hardware acceleration, but whether that feature will be present in Microsoft's ARM port of Windows remains to be seen.

**Comment by geerlingguy** [comment]
I think for now I'm going to shelve this idea as I'm planning on sticking with Linux on the Pi for now. If Microsoft officially adds better support to running their own ARM Windows version on non-OEM devices (like on Apple Silicon or Pis), I'll reconsider.

**Comment by mikewang01** [comment]
HI Guys,
Though this was an old and closed comments 
But After tons of struggling,  I have successfully, primitively, bring up pcie on CM4 io under both uefi and win11.
pcie2usb, pcie2ethernet. pcie2serial,  asm1184 switch, dGPU... that were available at my side could all be enumerated, and resource assigned.
of course, some may lack function driver.
My last experience focusses on Linux kernel too. This was really a tough process to deal with windows
