### ISSUE TITLE
InLine PCI-Express 2.0 SATA 6Gb/s controller, with 8x SATA 

### ISSUE THREAD

**Issue by ovz93br43v7** [geerlingguy/raspberry-pi-pcie-devices#79]
Can you probably try this SATA controller?: [InLine PCI-Express 2.0 SATA 6Gb/s controller, with 8x SATA ](https://www.inline-info.com/en/products/io-cards-cardreader/pcie/10007/inline-pci-express-2.0-sata-6gb/s-controller-with-8x-sata)

**Comment by TheGuyDanish** [comment]
The chip used in this card (Marvell 88SE9215) was already tested in #1. Most likely following the steps on this page would make the card work: https://pipci.jeffgeerling.com/cards_storage/iocrest-sata-3-marvell-9215.html
