### ISSUE TITLE
Add ModBerry, ClusBerry, and AI GATEWAY from Techbase

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-pcie-devices#86]
The [ModBerry 500 CM4](https://modberry.techbase.eu/compute-module-4/) is billed as an 'Industrial IoT Computer based on the Compute Module 4:

![500CM4](https://user-images.githubusercontent.com/481677/108800554-116fa280-7559-11eb-8e14-70adda605d25.jpg)

The [ClusBerry 9500-CM4](https://clusberry.techbase.eu) is billed as an 'Industrial Raspberry Pi Compute Module 4 Cluster'. It has a DIN rail case, a shared heatsink, and the standard set of modules includes an I/O board, a 'Communication Gateway', and an 'AI Gateway', all with different IO connections and purposes:

![clusberry8-2](https://user-images.githubusercontent.com/481677/108800698-7f1bce80-7559-11eb-8c9d-62617fa05abd.jpg)

The [AI GATEWAY 9500-CM4](https://modberry.techbase.eu/modberry/ai-gateway-series-with-compute-module-4-and-google-coral-tpu/) marries a CM4 with a Google Coral TPU, over PCIe (interestingly... I'm guessing they haven't been able to sell this through yet due to the PCIe driver bugs everyone's been running into—see #44:

![ai_gateway_promo1b-1-745x1024](https://user-images.githubusercontent.com/481677/108800921-05381500-755a-11eb-8e12-b8739cbbba77.jpg)

**Comment by geerlingguy** [comment]
Modberry, done!

**Comment by geerlingguy** [comment]
AI GATEWAY has been added too.

**Comment by punnypenguins** [comment]
@geerlingguy All three of these have been added now, right?

**Comment by geerlingguy** [comment]
@punnypenguins - Yep!
