### ISSUE TITLE
CM Hunter - CM4 Carrier Board with galvanically-isolated interfaces

### ISSUE THREAD

**Issue by sukhoi12** [geerlingguy/raspberry-pi-pcie-devices#88]
Raspberry Compute Module 4 Board with ISO Interfaces
Galvanically-Isolated Modbus, 1-Wire, CAN | LAN | HDMI | LCD | USB | RTC | RELAY | QT Application for small Displays | Open Source

This is not just another Raspberry PCB.
Not just IO Board. 
Open Source - Hardware and Software.

This Carrier board was created by engineers for engineers, creators, learners, hobbyist.

CM Hunter Integrates the most common communication protocols:

**•	RS485/Modbus isolated
•	CAN 2.0B isolated
•	1-Wire isolated
•	HDMI 2.0
•	ETHERNET Gigabit
•	USB 2.0
•	2.4 GHz, 5.0 GHz IEEE 802.11 b/g/n/ac wireless /some CM4 versions/
•	Bluetooth 5.0, BLE /some CM4 versions/**
+ Real Time Clock, Relay, LCD Display, SD/MMC card, Cooling Fan

CM Hunter is coming soon in **Kickstarter** It will participate in the crowdfunding activity soon, don't hesitate to give your support!

**Comment by geerlingguy** [comment]
@sukhoi12 - Do you have an image you could add here as well (just drag and drop in the original post or in a new comment); it sounds like an interesting board!

**Comment by sukhoi12** [comment]
![20210217_101515 – Копие – Копие](https://user-images.githubusercontent.com/33930434/108889934-9cae6e00-7615-11eb-9ce6-a5c3aebcf969.jpg)
![20210217_101515](https://user-images.githubusercontent.com/33930434/108889940-9e783180-7615-11eb-9b3d-b21d601fa3f0.jpg)
![20210217_101522](https://user-images.githubusercontent.com/33930434/108889956-a20bb880-7615-11eb-8ac0-6d3d7be917e7.jpg)
![20210217_101807](https://user-images.githubusercontent.com/33930434/108889966-a3d57c00-7615-11eb-9bf2-9b281c08d429.jpg)
![20210217_101821](https://user-images.githubusercontent.com/33930434/108889975-a637d600-7615-11eb-973b-e92921850424.jpg)
![20210217_101934](https://user-images.githubusercontent.com/33930434/108889983-a9cb5d00-7615-11eb-8ce4-ec9485e76f5d.jpg)

**Comment by davidindra** [comment]
Hello,
may I ask what's the state of this board? I didn't found the Kickstarter project and even the mentioned GitHub repository is empty. Please, can the schematics be obtained? @sukhoi12 
Thanks for your response!
