### ISSUE TITLE
Mcuzone CM4 board is available for purchase

### ISSUE THREAD

**Issue by freb** [geerlingguy/raspberry-pi-pcie-devices#89]
Looks like the Mcuzone CM4 carrier board has been modified and is now available for purchase:

<https://www.aliexpress.com/item/1005001972265702.html>

Per your comments in issue #25, looks like it should be moved to the production category.

**Comment by geerlingguy** [comment]
Good find! I'll try to get this updated on the site.

**Comment by geerlingguy** [comment]
Thanks, just got the site updated!
